### ISSUE TITLE
Upgrade RxJS

### ISSUE THREAD

**Issue by mikejancar** [Progressive-Insurance/oculr-ngx#133]
### Which of these features are related to this request?

maintenance

### Description

We need to upgrade RxJS to at least version 7.5.6 to gain the latest performance improvements for the `Observable` object.

### What do you propose?

Upgrade to version 7.5.6 and verify there are no breaking changes.

### Have you considered any alternatives?

No.

**Comment by michael-parkins** [comment]
I'll take this as I was upgrading all the packages with the major Angular upgrade.
